- name: Setup testing environment on Travis CI
  hosts: 127.0.0.1
  sudo: True
  vars:
    - cask_version: '0.7.2'
  tasks:
    - name: Install prerequisites to add package repositories
      apt: pkg=python-apt state=present
    - name: Add 3rd party repositories
      apt_repository: repo='{{item}}' update_cache=false state=present
      with_items:
        - ppa:cassou/emacs          # Stable Emacs 24.3
        - ppa:ubuntu-elisp/ppa      # Nightly Emacs trunk builds
    - name: apt update cache
      apt: update_cache=true force=yes
    - name: Install additional dependencies
      apt: name={{item}} state=latest install_recommends=false force=yes
      with_items:
        - emacs24-nox
    - name: Download Cask
      get_url: url=https://github.com/cask/cask/archive/v{{cask_version}}.tar.gz
               dest=/usr/src/cask-{{cask_version}}.tar.gz
    - name: Extract Cask
      unarchive: src=/usr/src/cask-{{cask_version}}.tar.gz copy=no dest=/opt/
                 creates=/opt/cask-{{cask_version}}/bin/cask
    - name: Put Cask into PATH
      file: path=/usr/local/bin/cask state=link
            src=/opt/cask-{{cask_version}}/bin/cask
